[package]
name = "littletsu/meowy-simulator"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.6.0"
Fusion = "elttob/fusion@0.2.0"
Signal = "sleitnick/signal@2.0.1"